#!/bin/bash

curl \
  -v \
  -X DELETE \
  "https://api.cloudflare.com/client/v4/zones/a8158665c3e36fccd6a96a6a628ec7a3/purge_cache" \
  -H "X-Auth-Email: aaron.r.stacy@gmail.com" \
  -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
  -H "Content-Type: application/json" \
  --data '{"purge_everything":true}' \
  2>&1 | grep -v X-Auth-Key
